CREATE TABLE users
(
    id            BIGINT generated by default as identity primary key,
    username      TEXT NOT NULL,
    password      TEXT NOT NULL,
    email         TEXT NOT NULL,
    role          TEXT NOT NULL
);

CREATE TABLE tasks
(
    id            BIGINT generated by default as identity primary key,
    title         TEXT NOT NULL,
    description   TEXT,
    username      TEXT NOT NULL,
    executor      TEXT NOT NULL,
    status        TEXT NOT NULL,
    priority      TEXT NOT NULL
);